//! `VioBus`: the resource bundle one estimator shares with the tasks around it.
//!
//! Two things cross into a backgrounded `StereoVio` without riding its single input edge: the
//! IMU samples (see [`crate::imu_channel`] for why they cannot ride it) and reset requests.
//! Both are shared state, and a resource bundle is copper's way of handing shared state to
//! several tasks: each bundle instance builds its own [`ImuQueue`] and [`ResetEpoch`], and the
//! RON binds them by name, so two estimators in one graph get two buses.
//!
//! ```ron
//! resources: [ ( id: "bus", provider: "cu_kornia_vio::VioBus" ) ],
//! tasks: [
//!     ( id: "imu_feed", type: "cu_kornia_vio::ImuFeed<32>",
//!       resources: { "imu": "bus.imu" } ),
//!     ( id: "vio", type: "cu_kornia_vio::StereoVio", background: true,
//!       resources: { "imu": "bus.imu", "epoch": "bus.reset_epoch" } ),
//! ],
//! ```

use std::sync::Arc;

use cu29::prelude::*;

use crate::imu_channel::ImuQueue;
use crate::reset::ResetEpoch;

/// The provider of an [`ImuQueue`] (`<id>.imu`) and a [`ResetEpoch`] (`<id>.reset_epoch`).
///
/// Takes no config; any key is refused, as with the tasks.
pub struct VioBus;

/// The resource ids of a [`VioBus`], generated by `bundle_resources!`.
#[doc(hidden)]
#[allow(missing_docs)]
pub mod bus_ids {
    use super::VioBus;
    use cu29::bundle_resources;

    bundle_resources!(VioBus: Imu, ResetEpoch);
}

use bus_ids::VioBusId;

impl ResourceBundle for VioBus {
    fn build(
        bundle: BundleContext<Self>,
        config: Option<&ComponentConfig>,
        manager: &mut ResourceManager,
    ) -> CuResult<()> {
        crate::config::deny_unknown_keys(config, "cu_kornia_vio::VioBus", &[])?;
        manager.add_shared(bundle.key(VioBusId::Imu), Arc::new(ImuQueue::new()))?;
        manager.add_shared(
            bundle.key(VioBusId::ResetEpoch),
            Arc::new(ResetEpoch::new()),
        )?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_bus_resource_names_match_the_documented_bindings() {
        assert_eq!(bus_ids::VIO_BUS_ID_NAMES, ["imu", "reset_epoch"]);
    }
}
